import type { Field } from "@buildnbuzz/buzzform";

export const arrayFieldProperties: Field[] = [
  {
    type: "tabs",
    ui: {
      variant: "line",
      spacing: "lg",
    },
    tabs: [
      {
        label: "General",
        fields: [
          {
            type: "text",
            name: "name",
            label: "Name",
            description: "Used as the key in form data (no spaces)",
            required: true,
            pattern: /^[a-zA-Z_][a-zA-Z0-9_]*$/,
            placeholder: "items",
          },
          {
            type: "text",
            name: "label",
            label: "Label",
            description: "Display label for the array",
            placeholder: "Items",
          },
          {
            type: "textarea",
            name: "description",
            label: "Description",
            description: "Help text shown below the label",
            rows: 2,
          },
          {
            type: "number",
            name: "minRows",
            label: "Minimum Rows",
            description: "Minimum number of items required",
            min: 0,
          },
          {
            type: "number",
            name: "maxRows",
            label: "Maximum Rows",
            description: "Maximum number of items allowed",
            min: 0,
          },
          {
            type: "switch",
            name: "hidden",
            label: "Hidden",
            description: "Hide this array from the form",
            ui: { alignment: "between" },
          },
          {
            type: "switch",
            name: "disabled",
            label: "Disabled",
            description: "Disable this array and all row controls",
            ui: { alignment: "between" },
          },
          {
            type: "switch",
            name: "readOnly",
            label: "Read Only",
            description: "Prevent adding, removing, and reordering rows",
            ui: { alignment: "between" },
          },
        ],
      },
      {
        label: "Behavior",
        fields: [
          {
            type: "switch",
            name: "ui.isSortable",
            label: "Sortable",
            description: "Allow row drag and drop reordering",
            ui: { alignment: "between" },
            defaultValue: true,
          },
          {
            type: "text",
            name: "ui.addLabel",
            label: "Add Button Label",
            description: "Text used for the add row action",
            placeholder: "Add Item",
          },
          {
            type: "text",
            name: "ui.rowLabelField",
            label: "Row Label Field",
            description: "Field name used as each row title",
            placeholder: "name",
          },
          {
            type: "switch",
            name: "ui.collapsed",
            label: "Start Collapsed",
            description: "Start the array container collapsed",
            ui: { alignment: "between" },
          },
          {
            type: "switch",
            name: "ui.rowsCollapsed",
            label: "Rows Collapsed",
            description: "Start all rows collapsed",
            ui: { alignment: "between" },
          },
          {
            type: "switch",
            name: "ui.confirmDelete",
            label: "Confirm Delete All",
            description: "Ask confirmation before deleting all rows",
            ui: { alignment: "between" },
          },
          {
            type: "text",
            name: "ui.emptyMessage",
            label: "Empty Message",
            description: "Message shown when no rows exist",
            placeholder: "No items added yet",
          },
          {
            type: "switch",
            name: "ui.showErrorBadge",
            label: "Show Error Badge",
            description: "Display total error count in the header",
            ui: { alignment: "between" },
            defaultValue: true,
          },
        ],
      },
      {
        label: "Style",
        fields: [
          {
            type: "select",
            name: "style.width",
            label: "Width",
            description: "Field width (useful in rows)",
            options: [
              { label: "Auto", value: "auto" },
              { label: "10%", value: "10%" },
              { label: "20%", value: "20%" },
              { label: "25%", value: "25%" },
              { label: "30%", value: "30%" },
              { label: "33%", value: "33.33%" },
              { label: "40%", value: "40%" },
              { label: "50%", value: "50%" },
              { label: "60%", value: "60%" },
              { label: "66%", value: "66.66%" },
              { label: "70%", value: "70%" },
              { label: "75%", value: "75%" },
              { label: "80%", value: "80%" },
              { label: "90%", value: "90%" },
              { label: "100%", value: "100%" },
            ],
          },
        ],
      },
    ],
  },
];
